Improved filtering for -e

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -41,7 +41,6 @@ deploy_default_config() {
         exit 1
     }
     f_default_conf="$d_default_conf/olint.conf"
-    echo
     if [ ! -f "$f_default_conf" ] || $force_deploy; then
         cp "$CURRENT_DIR"/default_config "$f_default_conf"
 
@@ -52,6 +51,16 @@ deploy_default_config() {
     else
         echo "Global config already pressent: $f_default_conf"
     fi
+    echo
+}
+
+deploy_default_ignore() {
+    cfg_file="$HOME"/.olint.conf
+    if [ ! -f "$cfg_file" ]; then
+        echo "Deploying a default 'ignore_project=yes' to home-dir"
+        echo "ignore_project=yes" >"$cfg_file"
+        echo
+    fi
 }
 
 deploy_plugins() {
@@ -60,15 +69,12 @@ deploy_plugins() {
     mkdir -p "$d_plugins"
 
     ! $force_deploy && [ -n "$(ls -A "$d_plugins")" ] && {
-        echo
         echo "Plugin folder: $d_plugins not empty"
         echo "No automatic instsall of plugins, current ones are in plugins/"
         return
     }
-    echo
     echo "Deploying plugins"
     rsync -ahP --exclude="*~" plugins/* "$d_plugins"
-
 }
 
 dependencied_debian() {
@@ -80,18 +86,18 @@ dependencies_alpine() {
 
     _s="$(command -v find)"
     if [ -z "$_s" ]; then
-	deps="$deps findutils"
+        deps="$deps findutils"
     else
-	realpath "$_s" | grep -q busybox && {
-	    echo "><> was busybox find"
-	    deps="$deps findutils"
-	}
+        realpath "$_s" | grep -q busybox && {
+            echo "><> was busybox find"
+            deps="$deps findutils"
+        }
     fi
 
     [ -n "$deps" ] && {
-	echo "WARNING: Missing Alpine dependencies, solve by running"
-	echo "apk add $deps"
-	exit 1
+        echo "WARNING: Missing Alpine dependencies, solve by running"
+        echo "apk add $deps"
+        exit 1
     }
 }
 
@@ -101,26 +107,26 @@ check_dependencies() {
     #
     #  Generic dependencies, with same names across distros
     #
-    command -v bash  >/dev/null || deps="$deps bash"
-    command -v file  >/dev/null || deps="$deps file"
+    command -v bash >/dev/null || deps="$deps bash"
+    command -v file >/dev/null || deps="$deps file"
     command -v rsync >/dev/null || deps="$deps rsync"
 
     if [ -f /etc/debian_version ]; then
-	dependencied_debian
+        dependencied_debian
     elif [ -f /etc/alpine-release ]; then
-	dependencies_alpine
+        dependencies_alpine
     fi
 
     [ -n "$deps" ] && {
-	if [ -z "$install_procedure" ]; then
-	    echo
-	    echo "WARNING: tools missing: $deps"
-	    echo "Not able to suggest how to deploy"
-	else
-	    echo "WARNING: Missing dependencies, solve by running"
-	    echo "$install_procedure $deps"
-	fi
-	exit 1
+        if [ -z "$install_procedure" ]; then
+            echo
+            echo "WARNING: tools missing: $deps"
+            echo "Not able to suggest how to deploy"
+        else
+            echo "WARNING: Missing dependencies, solve by running"
+            echo "$install_procedure $deps"
+        fi
+        exit 1
     }
 }
 
@@ -144,4 +150,5 @@ force_deploy=false
 
 deploy_app
 deploy_default_config
+deploy_default_ignore
 deploy_plugins
