reintroduced force deploy

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -92,7 +92,7 @@ deploy_default_config() {
     mkdir -p "$d_default_conf"
 
     f_default_conf="$d_default_conf/olint.conf"
-    if [ ! -f "$f_default_conf" ]; then
+    if $force_deploy || [ ! -f "$f_default_conf" ]; then
         cp "$REPO_DIR"/default_config "$f_default_conf"
 
         echo "A default config has been copied to: $f_default_conf"
@@ -126,14 +126,14 @@ deploy_plugins() {
 
     d_plugins="$d_default_conf"/plugins
     mkdir -p "$d_plugins"
-    [ -n "$(ls -A "$d_plugins")" ] && {
+    if [ -n "$(ls -A "$d_plugins")" ] && ! $force_deploy; then
         echo "Plugin folder has content, will not be overwritten"
         echo "  $d_plugins"
         return
-    }
+    fi
 
     if cmd_output="$(
-        rsync -ahP --exclude="*/" --exclude="*~" "$REPO_DIR"/plugins/* \
+        rsync -ahP --exclude="*/" --exclude="*~" --exclude="*#" "$REPO_DIR"/plugins/* \
             "$d_plugins" 2>&1
     )"; then
         echo "Default plugins installed to: $d_plugins"
@@ -164,19 +164,28 @@ deploy_default_ignore() {
 
 REPO_DIR="$(dirname -- "$0")"
 
+force_deploy=false
+
 check_dependencies
 get_app_destination
 
-[ "$1" = uninstall ] && {
+if [ "$1" = force ]; then
+    force_deploy=true
+elif [ "$1" = uninstall ]; then
     echo
     echo "-----   Uninstall olint   -----"
-    # if [
     rm -f "$d_app_dest"/olint || echo "no app installed"
     rm -rf "$HOME"/.config/olint
     rm -f "$HOME"/.olint.conf
     echo "Uninstall completed"
     exit 0
-}
+elif [ -n "$1" ]; then
+    echo "deploy [force/uninstall]"
+    echo
+    echo "ERROR: invalid option: $1"
+    exit 1    
+fi
+
 
 deploy_default_config
 deploy_app
