added more platforms

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -71,12 +71,13 @@ deploy_plugins() {
 
 }
 
-dependencies_alpine() {
-    deps=""
+dependencied_debian() {
+    install_procedure="apt install"
+}
 
-    echo "><> dependencies_alpine()"
-    command -v bash  >/dev/null || deps="$deps bash"
-    command -v file || deps="$deps file"
+dependencies_alpine() {
+    install_procedure="apk add"
+
     _s="$(command -v find)"
     if [ -z "$_s" ]; then
 	deps="$deps findutils"
@@ -86,7 +87,6 @@ dependencies_alpine() {
 	    deps="$deps findutils"
 	}
     fi
-    command -v rsync >/dev/null || deps="$deps rsync"
 
     [ -n "$deps" ] && {
 	echo "WARNING: Missing Alpine dependencies, solve by running"
@@ -96,10 +96,33 @@ dependencies_alpine() {
 }
 
 check_dependencies() {
-    [ -f /etc/alpine-release ] && dependencies_alpine
+    deps=""
+
+    #
+    #  Generic dependencies, with same names across distros
+    #
+    command -v bash  >/dev/null || deps="$deps bash"
+    command -v file  >/dev/null || deps="$deps file"
+    command -v rsync >/dev/null || deps="$deps rsync"
+
+    if [ -f /etc/debian_version ]; then
+	dependencied_debian
+    elif [ -f /etc/alpine-release ]; then
+	dependencies_alpine
+    fi
+
+    [ -n "$deps" ] && {
+	if [ -z "$install_procedure" ]; then
+	    echo
+	    echo "WARNING: tools missing: $deps"
+	    echo "Not able to suggest how to deploy"
+	else
+	    echo "WARNING: Missing dependencies, solve by running"
+	    echo "$install_procedure $deps"
+	fi
+	exit 1
+    }
 }
-
-
 
 #===============================================================
 #
