better handling of proj_linters, skipped when using -n

diff --git a/olint b/olint
--- a/olint
+++ b/olint
@@ -1378,9 +1378,13 @@ show_linter_action() {
 lint_file() {
     local linter="$1"
     local fname="$2"
-
+    local lint_pid
+    local lint_exit_status
+    
     dbg_print "lint_file($linter, $fname)" 4
     dbg_print " running: ${linter_cmd["$linter"]} $fname" 8
+
+    show_linter_action "$fname" "$linter"
     #
     #  In order to avoid some linters untrapping Ctrl-C
     #  they are run in the background. Then some code to ensure the
@@ -1395,6 +1399,30 @@ lint_file() {
         return 0
     else
         cat "$f_linter_output"
+        handle_linting_error
+    fi
+    return 1
+}
+
+lint_proj() {
+    local linter="$1"
+    local lint_pid
+    local lint_exit_status
+    
+    dbg_print "lint_proj($linter)" 4
+    dbg_print " running: ${linter_cmd["$linter"]}" 8
+
+    show_linter_action "* entire project *" "$linter_name"
+    #
+    #  In order to avoid some linters untrapping Ctrl-C
+    #  they are run in the background. Then some code to ensure the
+    #  exit code of the linter is captured
+    #
+    eval "${proj_linter_cmd["$linter"]}"
+    lint_exit_status=$?
+    if [[ "$lint_exit_status" -eq 0 ]]; then
+        return 0
+    else
         handle_linting_error
     fi
     return 1
@@ -1438,7 +1466,6 @@ lint_by_ext() {
                 dbg_print "$not_linting_msg" 4
                 return 0 # True - next file
             }
-            show_linter_action "$fname" "$linter"
             lint_file "$linter" "$fname" || linter_found_issue=true
         done
         if $linter_found; then
@@ -1675,14 +1702,16 @@ process_file_tree() {
             }
         }
     done
-    trap '' INT # abort capturing Ctrl-C
 
-    [[ ${#proj_linter_order[@]} -gt 0 ]] && {
-        for linter_name in "${proj_linter_order[@]}"; do
-            show_linter_action "* entire project *" "$linter_name"
-            eval "${proj_linter_cmd[$linter_name]}"
-        done
+    $do_lint_files && {
+        [[ ${#proj_linter_order[@]} -gt 0 ]] && {
+            for linter_name in "${proj_linter_order[@]}"; do
+                lint_proj "$linter_name"
+            done
+        }
     }
+    
+    trap '' INT # abort capturing Ctrl-C
 
     [[ $files_without_matching_linter -gt 0 ]] && {
         echo
