Improved Ctrl-C handling

diff --git a/olint b/olint
--- a/olint
+++ b/olint
@@ -642,7 +642,18 @@ lint_file() {
     local linter="$1"
     local fname="$2"
 
-    if eval "${linter_cmd["$linter"]}" "$fname" >"$f_linter_output" 2>&1; then
+    #
+    #  In order to avoid some linters untrapping Ctrl-C
+    #  they are run in the background. Then some code to ensure the
+    #  exit code of the linter is captured
+    #
+    eval "${linter_cmd["$linter"]}" "$fname" >"$f_linter_output" 2>&1 &
+    lint_pid=$!
+    wait "$lint_pid"
+    lint_exit_status=$?
+
+    # shellch eck disable=SC2181
+    if [[ "$lint_exit_status" -eq 0 ]]; then
         return 0 # True
     else
         cat "$f_linter_output"
@@ -816,9 +827,9 @@ process_file_tree() {
     dbg_print "process_file_tree()"
     ((dbg_indent++)) # increase indent until this returns
 
-    trap 'handle_ctrl_c INT' INT
-
     generate_list_of_files_to_process
+
+    trap 'handle_ctrl_c INT' INT
 
     orig_dbg_indent=$dbg_indent
     # only_check="files_to_check/profile"
@@ -872,7 +883,7 @@ process_file_tree() {
         }
     done
 
-    trap '' INT # abort capturing Ctrl-C
+    # trap '' INT # abort capturing Ctrl-C
 }
 
 show_help() {
