linting

diff --git a/plugins/shellcheck b/plugins/shellcheck
--- a/plugins/shellcheck
+++ b/plugins/shellcheck
@@ -1,6 +1,6 @@
 #!/bin/bash
 # This is sourced. Fake bang-path to help editors and linters
-# shellcheck disable=SC2034  # dont warn about unused variables
+# shellcheck disable=SC2034  # don't warn about unused variables
 
 # Installation methods;
 #  pip install shellcheck-py  # fails to install on iSH
@@ -16,8 +16,18 @@
 #  enable=all
 #  disable=SC2250,SC2312
 
-plugin_cmd="shellcheck -a -x --color=always -o all -e SC2250,SC2312"
 
+# SC2250 Prefer putting braces around variable references even when
+#        not strictly required.
+# SC2312 Consider invoking this command separately to avoid masking
+#        its return value (or use '|| true' to ignore).
+plugin_cmd="shellcheck -a -x --color=always -o all -e SC2250"
+
+if [ -f /etc/debian_version ] && grep -q 10 /etc/debian_version; then
+    # Debian 10 comes with shellcheck 0.5. lacking the -o option
+    plugin_cmd="shellcheck -a -x --color=always -e SC1117,SC2250"
+fi
+	
 # file extensions this plugin handles
 plugin_extensions=(
     .sh
